clusterServerCfg:
  masterURL:
  kubeConfig:
  leaseLockNamespace: velero
  leaseLockName: velero-volume-controller
veleroVolumeCfg:
  includeNamespaces: test
  excludeNamespaces:
  includeVolumeTypes: persistentVolumeClaim
  excludeVolumeTypes: